<?php
return array (
  'app' => 'Admin',
  'model' => 'jiaoyi',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '交易管理',
  'icon' => '',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Jiaoyi',
      'action' => 'dingdan',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '订单管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Jiaoyi',
      'action' => 'fuwu',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '服务商账户',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Jiaoyi',
      'action' => 'tixian',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '提现管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Jiaoyi',
      'action' => 'history',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '订单历史',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Jiaoyi',
      'action' => 'youhui',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '优惠券管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Jiaoyi',
      'action' => 'zhuandan',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '转单管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);