<?php
return array (
  'app' => 'Admin_new',
  'model' => 'fuwu',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '服务商管理',
  'icon' => '',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin_new',
      'model' => 'Fuwu',
      'action' => 'fuwu_list',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '服务商列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin_new',
      'model' => 'Fuwu',
      'action' => 'city',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '服务商服务城市',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin_new',
      'model' => 'Fuwu',
      'action' => 'project',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '服务商服务项目',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin_new',
      'model' => 'Fuwu',
      'action' => 'dingjia',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '服务商定价',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin_new',
      'model' => 'Fuwu',
      'action' => 'pinggu',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '服务商评估',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin_new',
      'model' => 'Fuwu',
      'action' => 'help',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '服务商帮助',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);