<?php
return array (
  'app' => 'Admin_new',
  'model' => 'Dingyue',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '订单管理',
  'icon' => '',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin_new',
      'model' => 'Dingyue',
      'action' => 'cheliang',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '车辆订阅',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin_new',
      'model' => 'Dingyue',
      'action' => 'count',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '违章统计推送记录',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin_new',
      'model' => 'Dingyue',
      'action' => 'weizhang',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '违章推送记录',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin_new',
      'model' => 'Dingyue',
      'action' => 'select',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '违章查询记录',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin_new',
      'model' => 'Dingyue',
      'action' => 'shuju',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '车辆数据库',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);